package it.eng.generate.project;

import it.eng.generate.ConfigCreateProject;
import it.eng.generate.DataBase;
import it.eng.generate.template.AbstractTemplate;

@Deprecated
public class TemplateJHipsterCostants extends AbstractTemplate {

	public TemplateJHipsterCostants(DataBase database) {
		super(database);
	}

	public String getTypeFile() {
		return "java";
	}

	/**
	 * This template has been generated by https://www.buildmystring.com
	 */
	public String getBody(){
		ConfigCreateProject conf = ConfigCreateProject.getIstance();
		String body = "\npackage "+ conf.getPackageclass() +";\n\n"+
		"/**\r\n" +
		" * JHipster imported constants.\r\n" +
		" */\r\n" +
		"public interface "+getClassName()+" {\r\n"+
		"    String SPRING_PROFILE_DEVELOPMENT = \"dev\";\r\n" +
		"    String SPRING_PROFILE_TEST = \"test\";\r\n" +
		"    String SPRING_PROFILE_PRODUCTION = \"prod\";\r\n" +
		"    // Spring profile used when deploying with Spring Cloud (used when deploying to CloudFoundry)\r\n" +
		"    String SPRING_PROFILE_CLOUD = \"cloud\";\r\n" +
		"    // Spring profile used when deploying to Heroku\r\n" +
		"    String SPRING_PROFILE_HEROKU = \"heroku\";\r\n" +
		"    // Spring profile used when deploying to Amazon ECS\r\n" +
		"    String SPRING_PROFILE_AWS_ECS = \"aws-ecs\";\r\n" +
		"    // Spring profile used to enable swagger\r\n" +
		"    String SPRING_PROFILE_SWAGGER = \"swagger\";\r\n" +
		"    // Spring profile used to disable running liquibase\r\n" +
		"    String SPRING_PROFILE_NO_LIQUIBASE = \"no-liquibase\";\r\n" +
		"    // Spring profile used when deploying to Kubernetes and OpenShift\r\n" +
		"    String SPRING_PROFILE_K8S = \"k8s\";\r\n" +
		"}\r\n";
		return body;
	}

	public String getClassName(){
		return "JHipsterConstants";
	}

	public String getTypeTemplate() {
		return "";
	}

	public String getSourceFolder() {
		return "src/main/java";
	}
}
